include("./random.jl")
include("./greedy_cycle.jl")
include("./nearest_neighbor.jl")
include("./greedy_2_regret.jl")
include("./local_greedy_search.jl")
include("./candidate_moves.jl")
inlcude("./deltas.jl")
